-- NEON/POSTGRESQL BATCH FOR TABLE: teachers
-- Drop table if exists (for re-runs)
DROP TABLE IF EXISTS teachers;

-- Create table (PostgreSQL syntax)
CREATE TABLE teachers (
    id SERIAL PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    last_name TEXT NOT NULL,
    first_name TEXT NOT NULL,
    title TEXT,
    email TEXT
);

-- Insert data
INSERT INTO teachers (id, code, last_name, first_name, title, email) VALUES
    (1,'JA','Aro','Jesah','Ms','jesaharo@westlandhigh.school.nz'),
    (2,'Ba','Bateup','Sarah','Ms','sarahbateup@westlandhigh.school.nz'),
    (3,'CY','Bradley','Conor','Mr','conorbradley@westlandhigh.school.nz'),
    (4,'JY','Bradley','Janna','Mrs','JannaBradley@westlandhigh.school.nz'),
    (5,'JB','Brownie','Jane','','janebrownie@westlandhigh.school.nz'),
    (6,'HB','Bruns','Hilke','Ms','hilkebruns@westlandhigh.school.nz'),
    (7,'FC','Cabanero','Joy','Ms','joycabanero@westlandhigh.school.nz'),
    (8,'CA','Callawick','Alexandra','Mrs','alexcallawick@westlandhigh.school.nz'),
    (9,'CP','Campion','Peter','Mr','PeterCampion@westlandhigh.school.nz'),
    (10,'Ch','Chinn','Gail','Mrs','GailChinn@westlandhigh.school.nz'),
    (11,'JK','Clark','James','Mr','JamesClark@westlandhigh.school.nz'),
    (12,'CL','Collins','Chris','Dr','chriscollins@westlandhigh.school.nz'),
    (13,'Col','Colman','Cassandra','Ms','CassandraColman@westlandhigh.school.nz'),
    (14,'CB','Conn','Belinda','','belindaconn@westlandhigh.school.nz'),
    (15,'JC','Cook','Justin','Mr','JustinCook@westlandhigh.school.nz'),
    (16,'JD','Dalgarno','John','Mr','johndalgarno@westlandhigh.school.nz'),
    (17,'Dk','Diplock','Maryke','Mrs','marykediplock@westlandhigh.school.nz'),
    (18,'SD','Dutt','Shalendra','Mr','ShalendraDutt@westlandhigh.school.nz'),
    (19,'AE','Evasco','Arleen','Ms','arleenevasco@westlandhigh.school.nz'),
    (20,'Gr','Greig','Annemarie','Mrs','annemariegreig@westlandhigh.school.nz'),
    (21,'Hj','Harrison','Janice','Mrs','janiceharrison@westlandhigh.school.nz'),
    (22,'MI','Hetherington','Michelle','Mrs','michellehetherington@westlandhigh.school.nz'),
    (23,'SH','Hilson','Sonica','Mrs','sonicahilson@westlandhigh.school.nz'),
    (24,'HE','Hulme','Monica','Ms','monicahulme@westlandhigh.school.nz'),
    (25,'TJ','Johnson','Tina','Ms','tinajohnson@westlandhigh.school.nz'),
    (26,'KN','Kelderman','Ino','Mr','inokelderman@westlandhigh.school.nz'),
    (27,'LI','King','Lachlan','Mr','LachlanKing@westlandhigh.school.nz'),
    (28,'Lr','Lauder','Fiona','Ms','fionalauder@westlandhigh.school.nz'),
    (29,'Le','Lee','Sheldon','Mr','sheldonlee@westlandhigh.school.nz'),
    (30,'Mn','Mallinson','Philippa','Ms','philippamallinson@westlandhigh.school.nz'),
    (31,'MA','Mathieson','Christine','Mrs','christinemathieson@westlandhigh.school.nz'),
    (32,'Mu','McClure','Bernie','Mrs','berniemcclure@westlandhigh.school.nz'),
    (33,'IMC','McDonald','Ian','Mr','IanMcDonald@westlandhigh.school.nz'),
    (34,'Am','McGrath','Anne','Mrs','annemcgrath@westlandhigh.school.nz'),
    (35,'HM','McKee','Holly','Ms','hollymckee@westlandhigh.school.nz'),
    (36,'Mc','McMullan','Raelene','Mrs','raelenemcmullan@westlandhigh.school.nz'),
    (37,'BMP','Mellsop','Brooke','Ms','brookemellsop@westlandhigh.school.nz'),
    (38,'JM','Minnaar','Johan','Mr','johanminnaar@westlandhigh.school.nz'),
    (39,'MM','Minnaar','Mariska','Mrs','mariskaminnaar@westlandhigh.school.nz'),
    (40,'GM','Monaheng','Gloria','Ms','gloriamonaheng@westlandhigh.school.nz'),
    (41,'SO','O''Malley','Siobhan','Mrs','siobhanomalley@westlandhigh.school.nz'),
    (42,'PH','Parikh','Brijen','Mr','sportshub@westlandhigh.school.nz'),
    (43,'BP','Parker','Brooke','Miss','brookeparker@westlandhigh.school.nz'),
    (44,'PI','Pinkerton','Anna','Mrs','annapinkerton@westlandhigh.school.nz'),
    (45,'VP','Pringle','Vanessa','Ms','vanessapringle@westlandhigh.school.nz'),
    (46,'PQ','Quilala','Paolo','Mr','PaoloQuilala@westlandhigh.school.nz'),
    (47,'MR','Ram','Mohinesh','Mr','mohineshram@westlandhigh.school.nz'),
    (48,'VR','Ram','Vikashni','Mrs','vikashniram@westlandhigh.school.nz'),
    (49,'Rs','Reeves','Adrienne','Mrs','adriennereeves@westlandhigh.school.nz'),
    (50,'RI','Rennie','Shanae','Miss','ShanaeRennie@westlandhigh.school.nz'),
    (51,'NR','Richards','Nic','Mr','principal@westlandhigh.school.nz'),
    (52,'BR','Roper','Bronte','Ms','bronteroper@westlandhigh.school.nz'),
    (53,'RY','Ryan','Rebecca','Ms','beckryan@westlandhigh.school.nz'),
    (54,'SR','Sadler','Janice','Ms','janicesadler@westlandhigh.school.nz'),
    (55,'GS','Smith','Gus','Mr','GusSmith@westlandhigh.school.nz'),
    (56,'TB','Talbot','Mike','Mr','miketalbot@westlandhigh.school.nz'),
    (57,'LT','Tame','Linda','Ms','LindaTame@westlandhigh.school.nz'),
    (58,'BT','Tapper','Ben','M','bentapper@westlandhigh.school.nz'),
    (59,'Tm','Thompson','Steve','Mr','stevethompson@westlandhigh.school.nz'),
    (60,'MTN','Thomson','Mike','Mr','mikethomson@westlandhigh.school.nz'),
    (61,'Jt','Thorpe','Judith','Ms','judiththorpe@westlandhigh.school.nz'),
    (62,'FUS','Usion','F','s','FUsion@westlandhigh.school.nz'),
    (63,'CV','Veale','Ciara','Ms','ciaraveale@westlandhigh.school.nz'),
    (64,'Ve','Veale','Kate','Ms','kateveale@westlandhigh.school.nz'),
    (65,'KV','Veale','Kristy','Ms','KristyVeale@westlandhigh.school.nz'),
    (66,'Wa','Waller','Michael','Mr','michaelwaller@westlandhigh.school.nz'),
    (67,'WY','Wastney','Rachel','Ms','rachelwastney@westlandhigh.school.nz'),
    (68,'JW','Webster','Janet','Ms','janetwebster@westlandhigh.school.nz'),
    (69,'We','Weepu','Christine','Mrs','christineweepu@westlandhigh.school.nz'),
    (70,'JE','Wellard','Jane','Miss','janewellard@westlandhigh.school.nz'),
    (73,'AS','Smith','Alice','Mrs','alice.smith@school.edu');

-- Note: SERIAL in PostgreSQL auto-increments id. If you want to continue auto-incrementing from the highest id, run:
-- SELECT setval('teachers_id_seq', (SELECT MAX(id) FROM teachers));
